## Image build
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as build

WORKDIR /worker

COPY src/Worker/Worker.csproj .

RUN dotnet restore

COPY src/Worker/ .

RUN dotnet publish -c Release -o /out Worker.csproj

## Image Run

FROM mcr.microsoft.com/dotnet/core/runtime:3.1

WORKDIR /worker

COPY --from=build /out .

CMD ["dotnet","Worker.dll"]

